name: Upload Codecov
on:
  - push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        if: github.ref === 'refs/heads/main'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: edwinlzs/chainflow