name: On Pull Request
run-name: ${{ github.actor }} has made a Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  Lint-and-Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered by ${{ github.event_name }}"
      - run: echo "Job running on ${{ runner.os }}"
      - run: echo "Current branch is ${{ github.ref }}"

      - name: Check out repo code
        uses: actions/checkout@v4

      - name: Installing pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.19'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - run: echo "Running unit tests..."
      - run: echo "This job's status is ${{ job.status }}"

      - name: Run markdown lint
        run: pnpm run markdownlint

      - name: Run linter
        run: pnpm run lint:fix
      
      - name: Run unit tests
        run: pnpm run test:coverage