name: On Push
run-name: ${{ github.actor }} has pushed commits
on:
  - push
jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered by ${{ github.event_name }}"
      - run: echo "Job running on ${{ runner.os }}"
      - run: echo "Current branch is ${{ github.ref }}"

      - name: Check out repo code
        uses: actions/checkout@v4 # clone repo to the runner

      - name: Installing pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3 # setup pnpm cache
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - run: echo "Running unit tests..."
      - run: echo "This job's status is ${{ job.status }}"
      
      - name: Run unit tests
        run: pnpm run test:coverage